package commands

import (
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/aviorstudio/gdam/internal/fsutil"
)

// The deps file is how an addon reaches the addons it declared without
// knowing where gdam put them. A dependency is hoisted to addons/<dir> when
// its tag agrees with the project's, and nested under the consumer when it
// does not; the consumer's source cannot hard-code either, so gdam writes
// one constant per dependency script with the resolved absolute path, and
// the addon preloads this file by a path relative to itself:
//
//	const Deps = preload("../.gdam/deps.gd")
//	var adapter := Deps.GdSession_credential_adapter.new()
//
// Rewritten on every install; never committed by the consuming project
// (it is derived) and never shipped in a release asset (the publisher
// excludes .gdam/).
const (
	depsDir  = ".gdam"
	depsFile = "deps.gd"
)

// writeDepsFile writes <copyDir>/.gdam/deps.gd for a copy whose
// dependencies resolved to the given project-relative paths. projectDir is
// where res:// points; scripts are enumerated from the dependency copies
// on disk, so the dependency must already be installed.
func writeDepsFile(projectDir, copyDir, consumer string, dependencies map[string]string) error {
	if len(dependencies) == 0 {
		return nil
	}
	var b strings.Builder
	b.WriteString("## Generated by gdam install. Do not edit: gdam rewrites it on every install.\n")
	b.WriteString("## Dependencies of " + consumer + ", at the paths this project resolved them to.\n")
	b.WriteString("## Reach a dependency's scripts through the constants below, never by a hard-coded res:// path.\n\n")
	names := make([]string, 0, len(dependencies))
	for name := range dependencies {
		names = append(names, name)
	}
	sort.Strings(names)
	b.WriteString("const PATHS: Dictionary = {\n")
	for _, name := range names {
		fmt.Fprintf(&b, "\t%q: %q,\n", name, "res://"+dependencies[name])
	}
	b.WriteString("}\n")
	used := map[string]bool{"PATHS": true}
	for _, name := range names {
		depDir := filepath.Join(projectDir, filepath.FromSlash(dependencies[name]))
		scripts, err := dependencyScripts(depDir)
		if err != nil {
			return err
		}
		if len(scripts) == 0 {
			continue
		}
		b.WriteString("\n")
		for _, script := range scripts {
			ident := constantName(name, script)
			for i := 2; used[ident]; i++ {
				ident = fmt.Sprintf("%s_%d", constantName(name, script), i)
			}
			used[ident] = true
			fmt.Fprintf(&b, "const %s = preload(%q)\n", ident, "res://"+path.Join(dependencies[name], script))
		}
	}
	dir := filepath.Join(copyDir, depsDir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	return fsutil.WriteFileAtomic(filepath.Join(dir, depsFile), []byte(b.String()), 0o644)
}

// dependencyScripts lists the .gd files of an installed addon copy that a
// consumer may preload: everything but the editor plugin entry point and
// the copy's own generated or nested content. Paths are slash-separated
// and relative to the copy.
func dependencyScripts(depDir string) ([]string, error) {
	var out []string
	err := filepath.WalkDir(depDir, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, relErr := filepath.Rel(depDir, p)
		if relErr != nil {
			return relErr
		}
		rel = filepath.ToSlash(rel)
		if d.IsDir() {
			if rel == depsDir || strings.HasPrefix(rel, depsDir+"/") {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(rel, ".gd") || rel == "plugin.gd" {
			return nil
		}
		out = append(out, rel)
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(out)
	return out, nil
}

// constantName derives a GDScript constant from an addon name and a script
// path: "@aviorstudio/gd-session" + "src/credential_adapter.gd" is
// GdSession_credential_adapter. The owner is dropped (two owners' addons
// of the same name in one consumer would be a stranger thing than a
// suffix), "src/" is dropped because every addon keeps its scripts there,
// and anything else in the path survives as underscores.
func constantName(addon, script string) string {
	repo := addon
	if i := strings.LastIndex(addon, "/"); i >= 0 {
		repo = addon[i+1:]
	}
	var pascal strings.Builder
	upper := true
	for _, r := range repo {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upper = true
			continue
		}
		if upper {
			pascal.WriteRune(unicode.ToUpper(r))
			upper = false
		} else {
			pascal.WriteRune(r)
		}
	}
	rest := strings.TrimSuffix(strings.TrimPrefix(script, "src/"), ".gd")
	var ident strings.Builder
	for _, r := range rest {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			ident.WriteRune(r)
		} else {
			ident.WriteRune('_')
		}
	}
	name := pascal.String()
	if name == "" || !unicode.IsLetter(rune(name[0])) {
		name = "Addon" + name
	}
	return name + "_" + ident.String()
}
